#!/usr/bin/env node
/**
  * afterloe.L - map-reduce-node/src/reduce
  *
  * Copyright(c) afterloe.L.
  * MIT Licensed
  *
  * Authors:
  *   afterloe.L <lm6289511@gmail.com> (https://github.com/afterloe)
  * Date:
  *   2017-7-27 09:33:31
  */
"use strict";