#!/usr/bin/env node
/**
  * afterloe.L - map-reduce-node/src/reduce
  *
  * Copyright(c) afterloe.L.
  * MIT Licensed
  *
  * Authors:
  *   afterloe.L <lm6289511@gmail.com> (https://github.com/afterloe)
  * Date:
  *   2017-7-27 09:33:31
  */
"use strict";

const readline = require('readline'); // 引入api
process.stdin.setEncoding('utf8'); // 设置输入流编码

// 初始化 行读取 组件
const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

// 编写行读取服务
rl.on('line', input => {
  // console.log(input);
});
