#!/usr/bin/env node
/**
  * afterloe.L - map-reduce-node/src/reduce
  *
  * Copyright(c) afterloe.L.
  * MIT Licensed
  *
  * Authors:
  *   afterloe.L <lm6289511@gmail.com> (https://github.com/afterloe)
  * Date:
  *   2017-7-27 09:33:31
  */
"use strict";

const readline = require('readline'); // 引入api
process.stdin.setEncoding('utf8'); // 设置输入流编码

const map = new Map();

// 初始化 行读取 组件
const rl = readline.createInterface({
  input: process.stdin,
});

const reduce = (item = []) => {
  const [name, plate] = item;
  const flag = map.get(name);
  if (flag) {
    flag.add(plate);
    map.set(name, flag);
  } else {
    map.set(name, new Set().add(plate));
  }
};

// 编写行读取服务
rl.on('line', input => {
  const _ = input.split('\t');
  if (_.length > 1) {
    reduce(_);
  }
});

process.stdin.on('end', () => {
  rl.close();
  for (let [key, value] of map.entries()) {
    console.log(`${key}\t${value.size}\t${Array.from(value).join(",")}`);
  }
});
